Repository bigpanther/shipanther, pull requests merged in 2020-12, with the labels that each got.

#138 Fix selector title
  lib/widgets/smart_select.dart
Labels: bug

#179 Ensure consistency of localization files
  .github/workflows/ci.yaml
  Makefile
  pubspec.lock
  pubspec.yaml
  test/localization_test.dart
Labels: code quality

#196 Localization
  i18n/intl_messages_en.arb
  i18n/intl_messages_pa.arb
  lib/helper/colon.dart
  lib/l10n/shipanther_localization.dart
  lib/screens/api_login.dart
  lib/screens/carrier/add_edit.dart
  lib/screens/carrier/home.dart
  lib/screens/carrier/list.dart
  lib/screens/container/add_edit.dart
  lib/screens/container/driver_list.dart
  lib/screens/container/home.dart
  lib/screens/container/list.dart
  lib/screens/customer/add_edit.dart
  lib/screens/customer/home.dart
  lib/screens/customer/list.dart
  lib/screens/customer_home.dart
  lib/screens/driver_home.dart
  lib/screens/none_home.dart
  lib/screens/order/add_edit.dart
  lib/screens/order/home.dart
  lib/screens/order/list.dart
  lib/screens/super_admin_home.dart
  lib/screens/tenant/add_edit.dart
  lib/screens/tenant/home.dart
  lib/screens/tenant/list.dart
  lib/screens/terminal/add_edit.dart
  lib/screens/terminal/list.dart
  lib/screens/user/add_edit.dart
  lib/screens/user/home.dart
  lib/screens/user/list.dart
  lib/screens/verify_email.dart
  lib/widgets/filter_button.dart
  lib/widgets/selectors.dart
  lib/widgets/shipanther_scaffold.dart
Labels: needs investigation
